version: '3'

services:
  desafio-angular:
    image: nginx:latest
    container_name: desafio-angular
    volumes:
    - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    - ./dist/desafio-angular:/usr/share/nginx/html
    ports:
     - 4200:80